name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  pages: write

concurrency:
  group: github-pages
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}resume.pdf

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Cache Docker images
      uses: ScribeMD/docker-cache@0.5.0
      with:
        key: docker-${{ runner.os }}-${{ github.workflow_sha }}

    - name: Build resume
      uses: xu-cheng/texlive-action@v3
      with:
        scheme: full
        run: |
          apk add --no-cache make
          make
          mkdir -p _site
          cp -t _site build/resume.pdf

    - name: Configure GitHub Pages
      uses: actions/configure-pages@v5

    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v4

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
